sudo: false
dist: trusty
language: java
jdk: openjdk-ea

matrix:
  include:
    - env: PLATFORM='linux'

    - env: PLATFORM='macos'
      os: osx

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro
  - echo "(compile foo (print (+ 40 2)))" | ./cplisp/bin/cplisp
  - java foo
