sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - wget --no-check-certificate https://github.com/forax/pro/releases/download/v0.11%2B13/pro-11.13-linux.tar.gz
  - tar -xzf pro-11.13-linux.tar.gz

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro
