sudo: false
dist: trusty
language: java
jdk: openjdk-ea

matrix:
  include:
    - env:
      - PLATFORM='linux'
      - PRO_SPECIAL_BUILD='early-access'
    - env:
      - PLATFORM='macos'
      - PRO_SPECIAL_BUILD='early-access'
      os: osx
  allow_failures:
    - os: osx

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - java pro_wrapper.java version

script:
  - ./pro/bin/java build.java
  - echo "(compile foo (print (+ 40 2)))" | ./cplisp/bin/cplisp
  - java foo
