sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - mvn install

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro
