sudo: false
dist: trusty
language: java
jdk: openjdk-ea

matrix:
  include:
    - env:
      - PLATFORM='linux'
    - env:
      - PLATFORM='macos'
      os: osx
    - env:
      - PLATFORM='linux'
      - PRO_EARLY_ACCESS='true'
    - env:
      - PLATFORM='macos'
      - PRO_EARLY_ACCESS='true'
      os: osx

matrix:
  allow_failures:
     - os: osx

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - java pro_wrapper.java version
  - pwd
  - ./pro/bin/java --version

script:
  - ./pro/bin/pro
  - echo "(compile foo (print (+ 40 2)))" | ./cplisp/bin/cplisp
  - java foo
